# Importing Libraries

In [4]:
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport

# Reading Dataset

In [5]:
df = pd.read_csv("creditcard.csv")

# EDA

In [6]:
df.shape

(284807, 31)

In [7]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

# Generating EDA Report

In [9]:
profile = ProfileReport(df)
profile.to_file("your_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\91850\anaconda3\lib\site-packages\scipy\stats\stats.py:4812: RuntimeWarning: overflow encountered in longlong_scalars
  (2 * xtie * ytie) / m + x0 * y0 / (9 * m * (size - 2)))


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
print(X_train)

[[ 1.30747000e+05  2.04716304e+00  1.07986610e-01 ... -8.50246556e-02
  -8.42920007e-02  7.70000000e-01]
 [ 8.13440000e+04  1.28240449e+00  4.59864448e-01 ... -1.01678633e-02
  -5.33248686e-03  1.79000000e+00]
 [ 1.59004000e+05 -4.14862511e-01  1.20257796e-02 ...  2.37627707e-01
   2.04342556e-01  5.95000000e+00]
 ...
 [ 7.66160000e+04  1.51260229e+00 -9.49435315e-01 ... -1.41537086e-03
   3.66494418e-03  3.49000000e+01]
 [ 9.72530000e+04  1.79886333e+00 -1.69979073e+00 ... -3.36155803e-02
  -3.24705125e-02  1.71310000e+02]
 [ 7.48870000e+04 -5.89399721e-01  7.47828393e-01 ...  8.65917860e-02
   1.18083774e-01  1.59900000e+01]]


In [13]:
print(y_train)

[0 0 0 ... 0 0 0]


In [14]:
print(X_test)

[[ 1.25821000e+05 -3.23333572e-01  1.05745525e+00 ...  1.08494430e-01
   1.61139167e-01  4.00000000e+01]
 [ 1.57235000e+05 -3.49718405e-01  9.32618570e-01 ...  7.68300272e-02
   1.75561960e-01  1.98000000e+00]
 [ 1.52471000e+05 -1.61471082e+00 -2.40656973e+00 ...  2.86285101e-01
   4.37321868e-01  9.60000000e+01]
 ...
 [ 5.74810000e+04  1.40322087e+00 -4.39300461e-01 ... -1.04050698e-02
   6.48925492e-03  1.00000000e+01]
 [ 1.53018000e+05 -3.23131065e+00  2.10313977e+00 ...  4.72312731e-01
  -1.92528808e-01  9.99900000e+01]
 [ 4.03190000e+04  1.25756139e+00 -7.24477151e-01 ... -1.01754487e-01
   1.19557412e-02  9.00000000e+01]]


In [15]:
print(y_test)

[0 0 0 ... 0 0 0]


# Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Training the Logistic Regression model on the Training set

In [17]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

# Predicting the Test set results

In [18]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[71071    11]
 [   41    79]]


0.9992696834358585

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71082
           1       0.88      0.66      0.75       120

    accuracy                           1.00     71202
   macro avg       0.94      0.83      0.88     71202
weighted avg       1.00      1.00      1.00     71202

